[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", ".pythonstartup", ".pythonrc"]
shebangs = ["python"] 
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#" 
language-servers = ["pyright", "ruff", "pylsp"]
auto-format = true
